# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.9.0.schema.json

PackageIdentifier: GAM-Team.GAM
PackageVersion: '7.02.00'
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.9.0
